/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/

#include <iostream>

int main() {
    int even_sum = 2;
    int max_fib_num = 4000000;

    int fib_num_cur = 2;
    int fib_num_prev = 1;

    while (fib_num_cur < max_fib_num) {
        int fib_num_cur_new = fib_num_cur + fib_num_prev;
        fib_num_prev = fib_num_cur;
        fib_num_cur = fib_num_cur_new;

        if (fib_num_cur_new % 2 == 0 && fib_num_cur_new < max_fib_num) {
            even_sum += fib_num_cur_new;
            //std::cout << "The sum is: " << even_sum << std::endl;
            //std::cout << "Added: " << fib_num_cur_new << std::endl;
        }
    }

    std::cout << "The sum is: " << even_sum << std::endl;
    return 0;
}
